# Generated by Django 4.0.2 on 2023-12-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.sub_color'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
