# Generated by Django 4.0.2 on 2023-11-22 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 22), null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
    ]
