# Generated by Django 4.0.2 on 2023-12-09 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_cart_sub_color_alter_cart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 9), null=True),
        ),
    ]
