# Generated by Django 4.0.2 on 2023-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_registration_addres_registration_joindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile',
            field=models.ImageField(blank=True, default='static\\images\\static_image\\Group 184.svg', null=True, upload_to='images/propic'),
        ),
    ]
