# Generated by Django 4.0.2 on 2023-11-23 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0003_alter_registration_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 23), null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile',
            field=models.ImageField(blank=True, default='static\\images\\static_image\\icon.svg', null=True, upload_to='images/propic'),
        ),
    ]
