# Generated by Django 4.0.2 on 2023-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0004_alter_registration_joindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
