# Generated by Django 4.0.2 on 2023-11-24 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0005_registration_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner', models.ImageField(blank=True, null=True, upload_to='images/banner')),
                ('top_link', models.CharField(blank=True, max_length=250, null=True)),
                ('middle_banner', models.ImageField(blank=True, null=True, upload_to='images/banner')),
                ('middle_link', models.CharField(blank=True, max_length=250, null=True)),
                ('bottom_banner1', models.ImageField(blank=True, null=True, upload_to='images/banner')),
                ('bottom_link1', models.CharField(blank=True, max_length=250, null=True)),
                ('bottom_banner2', models.ImageField(blank=True, null=True, upload_to='images/banner')),
                ('bottom_link2', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 24), null=True),
        ),
    ]
