# Generated by Django 4.0.2 on 2023-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
