# Generated by Django 4.0.2 on 2023-11-27 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0012_rename_text_cart_name_cart_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_item',
            name='item',
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 27), null=True),
        ),
    ]
