# Generated by Django 4.0.2 on 2023-11-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0015_orders_stage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_item',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.cart'),
        ),
    ]
