# Generated by Django 4.0.2 on 2023-11-28 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0018_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 28), null=True),
        ),
    ]
