# Generated by Django 4.0.2 on 2023-11-29 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0019_registration_location_alter_registration_joindate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='top_banner',
            new_name='top_banner1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='top_link',
            new_name='top_link1',
        ),
        migrations.AddField(
            model_name='banner',
            name='top_banner2',
            field=models.ImageField(blank=True, null=True, upload_to='images/banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_banner3',
            field=models.ImageField(blank=True, null=True, upload_to='images/banner'),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_link2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='top_link3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 29), null=True),
        ),
    ]
