# Generated by Django 4.0.2 on 2023-11-30 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0020_rename_top_banner_banner_top_banner1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='pin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 11, 30), null=True),
        ),
    ]
