# Generated by Django 4.0.2 on 2023-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0021_registration_country_registration_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='buying_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
