# Generated by Django 4.0.2 on 2023-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0022_sub_category_buying_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='buying_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
