# Generated by Django 4.0.2 on 2023-11-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0023_alter_sub_category_buying_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='buying_count',
            field=models.IntegerField(default=0),
        ),
    ]
