# Generated by Django 4.0.2 on 2023-12-01 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0024_alter_sub_category_buying_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='regno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='regno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 1), null=True),
        ),
    ]
