# Generated by Django 4.0.2 on 2023-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0026_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
