# Generated by Django 4.0.2 on 2023-12-05 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0027_registration_latitude_registration_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2023, 12, 5), null=True),
        ),
    ]
