# Generated by Django 4.0.2 on 2023-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0028_alter_events_name_alter_registration_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
