# Generated by Django 4.0.2 on 2023-12-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0029_item_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_chart',
            field=models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/size'),
        ),
        migrations.CreateModel(
            name='sub_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='sub_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.item')),
            ],
        ),
    ]
