# Generated by Django 4.0.2 on 2023-12-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0030_item_size_chart_sub_size_sub_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_chart',
            field=models.FileField(default='static/round_neck.jpg', upload_to='images/size'),
        ),
    ]
